
const arr = [
    {img:'./Airbnb/img (14).jpg',
    rating:'5.0',
    id: 0,
    reviewcount :'(6)',
    country:'USA',
    Title:'Life lessons with cater zafres',
    price:800,
    current: 'S'}, 
    {img:'./Airbnb/img (3).jpg',
    rating:'7.0',
    id: 1,
    reviewcount :'(3)',
    country:'USA',
    Title:'How to not get killed(thanos)',
    price:100,
    current: 'Online'},
    {img:'./Airbnb/img (1).jpg',
    rating:'9.0',
    id: 2,
    reviewcount :'(4)',
    country:'UK',
    Title:'Living with Deadpool',
    price:600,
    current: 'Offline'},
    {img:'./Airbnb/img (8).jpg',
    rating:'8.0',
    id: 3,
    reviewcount :'(5)',
    country:'UAE',
    Title:'Squidwards hack to life',
    price:400,
    current: 'Online'},
    {img:'./Airbnb/img (4).jpg',
    rating:'7.0',
    id: 4,
    reviewcount :'(6)',
    country:'Nigeria',
    Title:'Pandas advice for depression',
    price:1000,
    current: 'Sold out'},
    {img:'./Airbnb/img (5).jpg',
    rating:'5.0',
    id:5,
    reviewcount :'(6)',
    country:'(9ja)',
    Title:'How to avoid sapa',
    price:300,
    current: 'Offline'},
    {img:'./Airbnb/img (7).jpg',
    rating:'5.0',
    id:6,
    reviewcount :'(6)',
    country:'(9ja)',
    Title:'How to avoid sapa',
    price:300,
    current: 'Sold out'},
    
]
export default arr